version: '2.1'

services:
  

    selenium_hub:
        image: selenium/hub:3.8.1-aluminum
        container_name: selenium_hub
        privileged: true
        ports:
            - 4444:4444
        environment:
            - GRID_TIMEOUT=120000
            - GRID_BROWSER_TIMEOUT=120000
        networks:
            - selenium_grid_internal

    nodechrome1:
        image: selenium/node-chrome-debug:3.8.1-aluminum
        privileged: true
        depends_on:
            - selenium_hub
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=Europe/London
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
          - selenium_grid_internal

    nodechrome2:
        image: selenium/node-chrome-debug:3.8.1-aluminum
        privileged: true
        depends_on:
            - selenium_hub
        ports:
            - 5900
        environment:
            - no_proxy=localhost
            - TZ=Europe/London
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
          - selenium_grid_internal

  dotnet-test-1:
    image: stuartshay/imagegallery-client:2.0.0-test
    working_dir: /app/test/ImageGallery.Client.Test.UI
     depends_on:
      - selenium_hub
    environment:
      - TEST_FILTER="Category=Intergration"
      - ASPNETCORE_ENVIRONMENT=Staging
    command: "dotnet xunit -trait Category=Intergration -xml /artifacts/intergration-tests.xml"
    volumes: 
      - /home/jenkins/artifacts/imagegallery-client-selenium/test:/artifacts
      - /home/jenkins/artifacts/imagegallery-client-selenium/data:/app/artifacts
    networks:
      - selenium_grid_internal

networks:
  selenium_grid_internal:
