version: '2.1'

services:
  
  dotnet-test:
    image: stuartshay/imagegallery-api:2.0.0-test
    environment:
      - TEST_FILTER="Category=Intergration"
      - ASPNETCORE_ENVIRONMENT=Staging
    command: "/wait_for_it.sh -h database -p 1433 -t 0 -- dotnet xunit -trait Category=Intergration -xml /artifacts/intergration-tests.xml"
    depends_on:
      - database
    volumes: 
      - /home/jenkins/artifacts/imagegallery-api/test:/artifacts
    networks:
      - testing-imagegallery-api-network

  database:
    container_name: 'database'
    image: "microsoft/mssql-server-linux:2017-CU3"
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=An@a6AzqtDd%3JoYBL6BcvFKu
    networks:
      - testing-imagegallery-api-network

networks:
  testing-imagegallery-api-network:
