version: '2.1'

services:
  
 dotnet-imagegallery-client:
    image: stuartshay/imagegallery-client:2.0-build
    ports:
      - "80:44600"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - image-gallery-network

 redis:
    image: stuartshay/navigator-identity-redis
    networks:
      - image-gallery-network

networks:
  image-gallery-network:

