version: '2.1'

services:
  
 dotnet-imagegallery-client:
    image: stuartshay/imagegallery-client:2.0-build-v5
    ports:
      - "80:44600"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - image-gallery-release-network

 redis:
    image: stuartshay/navigator-identity-redis
    networks:
      - image-gallery-release-network

networks:
  image-gallery-release-network:

